# Generated by Django 5.2.8 on 2025-11-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название фонда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='funds/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Благотворительный фонд',
                'verbose_name_plural': 'Благотворительные фонды',
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание потребности')),
                ('category', models.CharField(choices=[('food', '🍎 Еда'), ('clothes', '👕 Одежда'), ('medicine', '💊 Лекарства'), ('household', '🏠 Хозтовары'), ('other', '❔ Другое')], max_length=20, verbose_name='Категория')),
                ('urgency', models.CharField(choices=[('low', '📗 Не срочно'), ('medium', '📐 Средняя срочность'), ('high', '📙 Срочно'), ('critical', '📕 Очень срочно')], default='medium', max_length=20, verbose_name='Срочность')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Имя контактного лица')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная заявка')),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на помощь',
                'verbose_name_plural': 'Заявки на помощь',
                'ordering': ['-created_at'],
            },
        ),
    ]
