# Generated by Django 5.2.8 on 2025-11-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название фонда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='funds/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Благотворительный фонд',
                'verbose_name_plural': 'Благотворительные фонды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок заявки')),
                ('description', models.TextField(verbose_name='Описание потребности')),
                ('category', models.CharField(choices=[('food', 'Еда'), ('clothes', 'Одежда'), ('medicine', 'Лекарства'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('contact_info', models.CharField(max_length=200, verbose_name='Контактная информация')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на помощь',
                'verbose_name_plural': 'Заявки на помощь',
                'ordering': ['-created_at'],
            },
        ),
    ]
